apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-number-app
  namespace: prime-number-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-number-app
  template:
    metadata:
      labels:
        app: prime-number-app
    spec:
      containers:
      - name: prime-number-app-d1
        image: prime-number-app-d1:latest
        imagePullPolicy: Never  # Ensures the image is not pulled from a remote registry
        ports:
        - containerPort: 8083  # Expose port 8083 for the application
        volumeMounts:
        - name: logs
          mountPath: /app/logs  # Mount a directory at /app
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"  # Set resource limits for better scheduling and management
      volumes:
      - name: logs
        emptyDir: {}  # Ephemeral volume, cleared when the pod is removed
