apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-number-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prime-number-app
  template:
    metadata:
      labels:
        app: prime-number-app
    spec:
      containers:
      - name: prime-number-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8083
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: logs
          mountPath: /app
      volumes:
      - name: logs
        emptyDir: {}
