apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterworkflowtemplates.argoproj.io
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  group: argoproj.io
  version: v1alpha1
  scope: Cluster
  names:
    kind: ClusterWorkflowTemplate
    listKind: ClusterWorkflowTemplateList
    plural: clusterworkflowtemplates
    shortNames:
    - clusterwftmpl
    - cwft
    singular: clusterworkflowtemplate
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              workflowSpec:
                type: object
                properties:
                  entrypoint:
                    type: string
                  templates:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        steps:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              templateRef:
                                type: object
                                properties:
                                  name:
                                    type: string
                  # Define other properties as needed
                required:
                  - entrypoint
                  - templates
            required:
              - workflowSpec
  # Optional: Additional validation
