apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workfloweventbindings.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: WorkflowEventBinding
    listKind: WorkflowEventBindingList
    plural: workfloweventbindings
    shortNames:
    - wfeb
    singular: workfloweventbinding
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              workflowSpec:
                type: object
                properties:
                  entrypoint:
                    type: string
                  templates:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        steps:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              templateRef:
                                type: object
                                properties:
                                  name:
                                    type: string
                  # Define other properties as needed
                required:
                  - entrypoint
                  - templates
            required:
              - workflowSpec
  # Optional: Additional validation
