apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflows.argoproj.io
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: Status of the workflow
    name: Status
    type: string
  - JSONPath: .status.startedAt
    description: When the workflow was started
    format: date-time
    name: Age
    type: date
  group: argoproj.io
  names:
    kind: Workflow
    listKind: WorkflowList
    plural: workflows
    shortNames:
    - wf
    singular: workflow
  scope: Namespaced
  subresources: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              workflowSpec:
                type: object
                properties:
                  entrypoint:
                    type: string
                  templates:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        steps:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              templateRef:
                                type: object
                                properties:
                                  name:
                                    type: string
                  # Define other properties as needed
                required:
                  - entrypoint
                  - templates
            required:
              - workflowSpec
  # Optional: Additional validation
