apiVersion: v1
kind: Secret
metadata:
  name: datadog-secrets
  namespace: datadog
type: Opaque
data:
  api-key: #set the api-key, inject via Key-vault
  app-key: #set the app-key, inject via Key-vault
