replicaCount: 1

image:
  repository: prime-number-app-d1
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8083

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

namespace: prime-number-app

volume:
  mountPath: /app/logs

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuUtilizationPercentage: 80

ingress:
  enabled: false  # Set to true to enable ingress
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []  # Define TLS settings here if needed