apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-config
  namespace: {{ .Values.namespace }}
data:
  datadog.yaml: |
    ## Provides autodetected defaults, for vanilla Docker environments,
    ## please see datadog.yaml.example for all supported options
    apm_config:
      apm_non_local_traffic: true
    jmx_use_container_support: true
    logs_enabled: true
    logs:
      - type: file
        path: /app/prime_number.log
        service: prime_number_app
        source: python
    listeners:
      - name: docker
    config_providers:
      - name: docker
        polling: true
    logs_config:
      container_collect_all: true
    process_config:
      process_collection:
        enabled: true
    system_probe_config:
      enabled: true
    site: datadoghq.eu
