apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      labels:
        app: datadog-agent
    spec:
      containers:
        - name: datadog-agent
          image: gcr.io/datadoghq/agent:7
          env:
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secrets
                  key: api_key
            - name: DD_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secrets
                  key: app_key
            - name: DD_SITE
              value: "datadoghq.eu"
            - name: DD_LOGS_ENABLED
              value: "true"
            - name: DD_LOGS_CONFIG_LOGS_ENABLED
              value: "true"
            - name: DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED
              value: "true"
          volumeMounts:
            - name: datadog-config
              mountPath: /etc/datadog-agent
      volumes:
        - name: datadog-config
          hostPath:
            path: /Users/arunkumar/app/datadog
            type: Directory
