apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prime-number-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: prime-number-app
  template:
    metadata:
      labels:
        app: prime-number-app
    spec:
      containers:
      - name: prime-number-app-d1
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        volumeMounts:
        - name: logs
          mountPath: {{ .Values.volume.mountPath }}
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
      volumes:
      - name: logs
        emptyDir: {}
